export interface Bank {
  code: string;
  name: string;
  fullName: string;
  logo: string;
  bin: string;
}

export const BANKS: Bank[] = [
  {"code":"ABB","name":"ABB","fullName":"Ngân hàng TMCP An Bình","logo":"https://vietqr.net/portal-service/resources/icons/ABB.png","bin":"970425"},
  {"code":"ACB","name":"ACB","fullName":"Ngân hàng TMCP Á Châu","logo":"https://vietqr.net/portal-service/resources/icons/ACB.png","bin":"970416"},
  {"code":"BAB","name":"BAB","fullName":"Ngân hàng TMCP Bắc Á","logo":"https://vietqr.net/portal-service/resources/icons/BAB.png","bin":"970409"},
  {"code":"BIDC","name":"BIDC","fullName":"Ngân hàng Đầu Tư Và Phát Triển Campuchia - Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/BIDC.png","bin":"970456"},
  {"code":"BIDV","name":"BIDV","fullName":"Ngân hàng TMCP Đầu tư và Phát triển Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/BIDV.png","bin":"970418"},
  {"code":"BNP_HCM","name":"BNP HCM","fullName":"Ngân hàng BNP Paribas – Chi nhánh Thành phố Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/BNP.png","bin":"970424"},
  {"code":"BNP_HN","name":"BNP HN","fullName":"Ngân hàng BNP Paribas – Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/BNP.png","bin":"970424"},
  {"code":"BVB","name":"BVB","fullName":"Ngân hàng TMCP Bảo Việt","logo":"https://vietqr.net/portal-service/resources/icons/BVB.png","bin":"970438"},
  {"code":"CAKE","name":"CAKE","fullName":"TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank","logo":"https://vietqr.net/portal-service/resources/icons/CAKE.png","bin":"546034"},
  {"code":"CBB","name":"CBB","fullName":"Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/CBB.png","bin":"970444"},
  {"code":"CIMB","name":"CIMB","fullName":"Ngân hàng TNHH MTV CIMB Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/CIMB.png","bin":"422589"},
  {"code":"CITIBANK","name":"CITIBANK","fullName":"Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/CITIBANK.png","bin":"533948"},
  {"code":"COOPBANK","name":"COOPBANK","fullName":"Ngân hàng Hợp tác xã Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/COOPBANK.png","bin":"970446"},
  {"code":"CUBHCM","name":"CUBHCM","fullName":"Ngân hàng Cathay United Bank – Chi nhánh Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/CUB.png","bin":"970457"},
  {"code":"DBS","name":"DBS","fullName":"DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/DBS.png","bin":"796500"},
  {"code":"DOB","name":"DOB","fullName":"Ngân hàng TNHH Một thành viên số Vikki","logo":"https://vietqr.net/portal-service/resources/icons/DOB.png","bin":"970406"},
  {"code":"EIB","name":"EIB","fullName":"Ngân hàng TMCP Xuất Nhập khẩu Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/EIB.png","bin":"970431"},
  {"code":"GPB","name":"GPB","fullName":"Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu","logo":"https://vietqr.net/portal-service/resources/icons/GPB.png","bin":"970408"},
  {"code":"HDB","name":"HDB","fullName":"Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/HDB.png","bin":"970437"},
  {"code":"HLBVN","name":"HLBVN","fullName":"Ngân hàng TNHH MTV Hong Leong Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/HLBVN.png","bin":"970442"},
  {"code":"HSBC","name":"HSBC","fullName":"Ngân hàng TNHH MTV HSBC (Việt Nam)","logo":"https://vietqr.net/portal-service/resources/icons/HSBC.png","bin":"458761"},
  {"code":"IBK_HCM","name":"IBK HCM","fullName":"Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/IBK.png","bin":"970455"},
  {"code":"IBK_HN","name":"IBK HN","fullName":"Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/IBK.png","bin":"970455"},
  {"code":"ICB","name":"ICB","fullName":"Ngân hàng TMCP Công thương Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/ICB.png","bin":"970415"},
  {"code":"ICBC","name":"ICBC","fullName":"Ngân hàng Công thương Trung Quốc – Chi nhánh thành phố Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/ICBC.png","bin":"970452"},
  {"code":"IVB","name":"IVB","fullName":"Ngân hàng TNHH Indovina","logo":"https://vietqr.net/portal-service/resources/icons/IVB.png","bin":"970434"},
  {"code":"KBHCM","name":"KBHCM","fullName":"Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/KB.png","bin":"970462"},
  {"code":"KBHN","name":"KBHN","fullName":"Ngân hàng Kookmin - Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/KB.png","bin":"970462"},
  {"code":"KBank","name":"KBank","fullName":"Ngân hàng Đại chúng TNHH Kasikornbank","logo":"https://vietqr.net/portal-service/resources/icons/KBank.png","bin":"668888"},
  {"code":"KEBHANAHCM","name":"KEBHANAHCM","fullName":"Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/KEBHANAHCM.png","bin":"970466"},
  {"code":"KEBHANAHN","name":"KEBHANAHN","fullName":"Ngân hàng KEB Hana – Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/KEBHANAHN.png","bin":"970466"},
  {"code":"KLB","name":"KLB","fullName":"Ngân hàng TMCP Kiên Long","logo":"https://vietqr.net/portal-service/resources/icons/KLB.png","bin":"970452"},
  {"code":"LPBANK","name":"LPBANK","fullName":"Ngân hàng TMCP Lộc Phát Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/LPBANK.png","bin":"970449"},
  {"code":"MAFC","name":"MAFC","fullName":"Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)","logo":"https://vietqr.net/portal-service/resources/icons/MAFC.png","bin":"977777"},
  {"code":"MB","name":"MB","fullName":"Ngân hàng TMCP Quân đội","logo":"https://vietqr.net/portal-service/resources/icons/MB.png","bin":"970422"},
  {"code":"MBV","name":"MBV","fullName":"Ngân hàng TNHH MTV Việt Nam Hiện Đại","logo":"https://vietqr.net/portal-service/resources/icons/MBV.png","bin":"970426"},
  {"code":"MSB","name":"MSB","fullName":"Ngân hàng TMCP Hàng Hải","logo":"https://vietqr.net/portal-service/resources/icons/MSB.png","bin":"970426"},
  {"code":"MVAS","name":"MVAS","fullName":"Trung tâm Dịch vụ số Mobifone – Chi nhánh Tổng Công ty viễn thông Mobifone","logo":"https://vietqr.net/portal-service/resources/icons/MVAS.png","bin":"963388"},
  {"code":"NAB","name":"NAB","fullName":"Ngân hàng TMCP Nam Á","logo":"https://vietqr.net/portal-service/resources/icons/NAB.png","bin":"970428"},
  {"code":"NCB","name":"NCB","fullName":"Ngân hàng TMCP Quốc Dân","logo":"https://vietqr.net/portal-service/resources/icons/NCB.png","bin":"970419"},
  {"code":"NHB_HN","name":"NHB HN","fullName":"Ngân hàng Nonghyup - Chi nhánh Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/NHB HN.png","bin":"801011"},
  {"code":"OCB","name":"OCB","fullName":"Ngân hàng TMCP Phương Đông","logo":"https://vietqr.net/portal-service/resources/icons/OCB.png","bin":"970448"},
  {"code":"PBVN","name":"PBVN","fullName":"Ngân hàng TNHH MTV Public Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/PBVN.png","bin":"970439"},
  {"code":"PGB","name":"PGBank","fullName":"Ngân hàng TMCP Thịnh vượng và Phát triển","logo":"https://vietqr.net/portal-service/resources/icons/PGB.png","bin":"970430"},
  {"code":"PVCB","name":"PVCB","fullName":"Ngân hàng TMCP Đại Chúng Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/PVCB.png","bin":"970412"},
  {"code":"PVCB_PAY","name":"PVCB Pay","fullName":"Ngân hàng số PVcomBank","logo":"https://vietqr.net/portal-service/resources/icons/PVCB Pay.png","bin":"970412"},
  {"code":"SCB","name":"SCB","fullName":"Ngân hàng TMCP Sài Gòn","logo":"https://vietqr.net/portal-service/resources/icons/SCB.png","bin":"970429"},
  {"code":"SCVN","name":"SCVN","fullName":"Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/SCVN.png","bin":"970410"},
  {"code":"SEAB","name":"SEAB","fullName":"Ngân hàng TMCP Đông Nam Á","logo":"https://vietqr.net/portal-service/resources/icons/SEAB.png","bin":"970440"},
  {"code":"SGICB","name":"SGICB","fullName":"Ngân hàng TMCP Sài Gòn Công Thương","logo":"https://vietqr.net/portal-service/resources/icons/SGICB.png","bin":"970400"},
  {"code":"SHB","name":"SHB","fullName":"Ngân hàng TMCP Sài Gòn - Hà Nội","logo":"https://vietqr.net/portal-service/resources/icons/SHB.png","bin":"970443"},
  {"code":"SHBVN","name":"SHBVN","fullName":"Ngân hàng TNHH MTV Shinhan Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/SHBVN.png","bin":"970424"},
  {"code":"STB","name":"STB","fullName":"Ngân hàng TMCP Sài Gòn Thương Tín","logo":"https://vietqr.net/portal-service/resources/icons/STB.png","bin":"970403"},
  {"code":"TCB","name":"TCB","fullName":"Ngân hàng TMCP Kỹ thương Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/TCB.png","bin":"970407"},
  {"code":"TIMO","name":"TIMO","fullName":"Ngân hàng số Timo by Ban Viet Bank","logo":"https://vietqr.net/portal-service/resources/icons/TIMO.png","bin":"963388"},
  {"code":"TNEX","name":"TNEX","fullName":"TNEX by MSB","logo":"https://vietqr.net/portal-service/resources/icons/TNEX.png","bin":"970426"},
  {"code":"TPB","name":"TPB","fullName":"Ngân hàng TMCP Tiên Phong","logo":"https://vietqr.net/portal-service/resources/icons/TPB.png","bin":"970423"},
  {"code":"UOB","name":"UOB","fullName":"Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh","logo":"https://vietqr.net/portal-service/resources/icons/UOB.png","bin":"970458"},
  {"code":"UBANK","name":"Ubank","fullName":"TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank","logo":"https://vietqr.net/portal-service/resources/icons/Ubank.png","bin":"546035"},
  {"code":"VAB","name":"VAB","fullName":"Ngân hàng TMCP Việt Á","logo":"https://vietqr.net/portal-service/resources/icons/VAB.png","bin":"970427"},
  {"code":"VBA","name":"VBA","fullName":"Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/VBA.png","bin":"970405"},
  {"code":"VBSP","name":"VBSP","fullName":"Ngân hàng Chính sách Xã hội","logo":"https://vietqr.net/portal-service/resources/icons/VBSP.png","bin":"999888"},
  {"code":"VCB","name":"VCB","fullName":"Ngân hàng TMCP Ngoại Thương Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/VCB.png","bin":"970436"},
  {"code":"VCCB","name":"VCCB","fullName":"Ngân hàng TMCP Bản Việt","logo":"https://vietqr.net/portal-service/resources/icons/VCCB.png","bin":"970454"},
  {"code":"VIB","name":"VIB","fullName":"Ngân hàng TMCP Quốc tế Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/VIB.png","bin":"970441"},
  {"code":"VIETBANK","name":"VIETBANK","fullName":"Ngân hàng TMCP Việt Nam Thương Tín","logo":"https://vietqr.net/portal-service/resources/icons/VIETBANK.png","bin":"970433"},
  {"code":"VNPTMONEY","name":"VNPTMONEY","fullName":"Trung tâm dịch vụ tài chính số VNPT - VNPT Fintech","logo":"https://vietqr.net/portal-service/resources/icons/VNPTMONEY.png","bin":"971005"},
  {"code":"VPB","name":"VPB","fullName":"Ngân hàng TMCP Việt Nam Thịnh Vượng","logo":"https://vietqr.net/portal-service/resources/icons/VPB.png","bin":"970432"},
  {"code":"VRB","name":"VRB","fullName":"Ngân hàng Liên doanh Việt - Nga","logo":"https://vietqr.net/portal-service/resources/icons/VRB.png","bin":"970421"},
  {"code":"VTLMONEY","name":"VTLMONEY","fullName":"Tổng Công ty Dịch vụ số Viettel","logo":"https://vietqr.net/portal-service/resources/icons/VTLMONEY.png","bin":"971006"},
  {"code":"WVN","name":"WVN","fullName":"Ngân hàng TNHH MTV Woori Việt Nam","logo":"https://vietqr.net/portal-service/resources/icons/WVN.png","bin":"970457"}
];
